# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Linux on Pipa Wiki
site_url: https://pipa-linux-wiki.github.io/
repo_url: https://github.com/rr1111/pipa-linux-wiki
repo_name: rr1111/pipa-linux-wiki
edit_uri: edit/master/docs/
theme:
  name: material

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - content.action.edit

  icon:
    logo: material/tablet
    repo: simple/github
    edit: material/pencil

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.footer

extra:
  social:
    - icon: simple/telegram
      link: https://t.me/pipa_mainline
    - icon: simple/github
      link: https://github.com/rr1111/pipa-linux-wiki



markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
